// Package model contains the types for schema 'homework'.
package model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"errors"
	"time"
)

// Demo represents a row from 'homework.demo'.
type Demo struct {
	AutoID int             `json:"auto_id"` // auto_id
	User   sql.NullString  `json:"user"`    // user
	Money  sql.NullFloat64 `json:"money"`   // money
	Time   time.Time       `json:"time"`    // time

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Demo exists in the database.
func (d *Demo) Exists() bool {
	return d._exists
}

// Deleted provides information if the Demo has been deleted from the database.
func (d *Demo) Deleted() bool {
	return d._deleted
}

// Insert inserts the Demo to the database.
func (d *Demo) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if d._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO homework.demo (` +
		`user, money, time` +
		`) VALUES (` +
		`?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, d.User, d.Money, d.Time)
	res, err := db.Exec(sqlstr, d.User, d.Money, d.Time)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	d.AutoID = int(id)
	d._exists = true

	return nil
}

// Update updates the Demo in the database.
func (d *Demo) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !d._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if d._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE homework.demo SET ` +
		`user = ?, money = ?, time = ?` +
		` WHERE auto_id = ?`

	// run query
	XOLog(sqlstr, d.User, d.Money, d.Time, d.AutoID)
	_, err = db.Exec(sqlstr, d.User, d.Money, d.Time, d.AutoID)
	return err
}

// Save saves the Demo to the database.
func (d *Demo) Save(db XODB) error {
	if d.Exists() {
		return d.Update(db)
	}

	return d.Insert(db)
}

// Delete deletes the Demo from the database.
func (d *Demo) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !d._exists {
		return nil
	}

	// if deleted, bail
	if d._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM homework.demo WHERE auto_id = ?`

	// run query
	XOLog(sqlstr, d.AutoID)
	_, err = db.Exec(sqlstr, d.AutoID)
	if err != nil {
		return err
	}

	// set deleted
	d._deleted = true

	return nil
}

// DemoByAutoID retrieves a row from 'homework.demo' as a Demo.
//
// Generated from index 'demo_auto_id_pkey'.
func DemoByAutoID(db XODB, autoID int) (*Demo, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`auto_id, user, money, time ` +
		`FROM homework.demo ` +
		`WHERE auto_id = ?`

	// run query
	XOLog(sqlstr, autoID)
	d := Demo{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, autoID).Scan(&d.AutoID, &d.User, &d.Money, &d.Time)
	if err != nil {
		return nil, err
	}

	return &d, nil
}

// DemosByUser retrieves a row from 'homework.demo' as a Demo.
//
// Generated from index 'user'.
func DemosByUser(db XODB, user sql.NullString) ([]*Demo, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`auto_id, user, money, time ` +
		`FROM homework.demo ` +
		`WHERE user = ?`

	// run query
	XOLog(sqlstr, user)
	q, err := db.Query(sqlstr, user)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Demo{}
	for q.Next() {
		d := Demo{
			_exists: true,
		}

		// scan
		err = q.Scan(&d.AutoID, &d.User, &d.Money, &d.Time)
		if err != nil {
			return nil, err
		}

		res = append(res, &d)
	}

	return res, nil
}
