version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
       - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
  
  dbrestore:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DC_DB_HOST=${DC_DB_HOST}
      - DC_DB_SSL_MODE=${DC_DB_SSL_MODE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ../db:/db
      - ../tools:/tools
    depends_on:
      - db
    links:
      - db
    command: "./tools/deploy.sh dbrestore"
    # running on container

  server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - "9090:9090"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DC_DB_HOST=${DC_DB_HOST}
      - DC_DB_SSL_MODE=${DC_DB_SSL_MODE}
    volumes:
      # abs dirctory cause this use here .env, no $GOPATH
      - ../logs:/go/src/github.com/sundayfun/go-web/logs
      # - ../logs:$GOPATH/src/github.com/sundayfun/go-web/logs
    depends_on:
      - db
    links:
      - db
    restart: always
volumes:
  mysql_data: