version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql_data_test:/var/lib/mysql
    ports:
       - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
  
  dbrestore:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - VIMI_DB_HOST=${VIMI_DB_HOST}
      - VIMI_DB_SSL_MODE=${VIMI_DB_SSL_MODE}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ../db:/db
      - ../tools:/tools
    depends_on:
      - db
    links:
      - db
    command: "./tools/deploy.sh dbrestore"
    # running on container
  
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    restart: always

  server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - "9090:9090"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - VIMI_DB_HOST=${VIMI_DB_HOST}
      - VIMI_DB_SSL_MODE=${VIMI_DB_SSL_MODE}
      - Telegram_Token=${Telegram_Token}
      - Redis_Host=${Redis_Host}
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTPS_PROXY}
    # args:
    #   - http_proxy=${PROXY} # export PROXY=http://zz:xx if need proxy to build
    #   - https_proxy=${PROXY}
    volumes:
      # abs dirctory cause this use here .env, no $GOPATH
      - ../logs:/go/src/github.com/sundayfun/go-web/logs
      # - ../logs:$GOPATH/src/github.com/sundayfun/go-web/logs
    depends_on:
      - redis
    restart: always

  sslocal:
    image: ahui/sslocal
    ports:
    - 127.0.0.1:1080:1080
    restart: always
    volumes:
    - ./sslocal-config.json:/etc/sslocal.json
    command: "-c /etc/sslocal.json"

volumes:
  mysql_data_test:
  redis_data:
